### ISSUE TITLE
Wrap exception nicely

### ISSUE THREAD

**Issue by bokobza** [stratisproject/FederatedSidechains#251]
This is hown to the console:
```
fail: Stratis.FederatedPeg.Features.FederationGateway.SourceChain.RestBlockTipSender[0]
      Failed to send {
        "Hash": "0adaa0149db0bcde3a112d908d399858df2acb1b3d262356370a3e737528e20b",
        "Height": 588,
        "MatureConfirmations": 1
      }
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Stratis.FederatedPeg.Features.FederationGateway.SourceChain.RestSenderBase.SendAsync[T](T model, String route) in D:\GitHub\FederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\SourceChain\RestSenderBase.cs:line 46
fail: Stratis.FederatedPeg.Features.FederationGateway.SourceChain.RestMaturedBlockSender[0]
      Failed to send {
        "Deposits": [],
        "Block": {
          "BlockHash": "f5b20f4f2db4682ee9035db5674e09a54ae421098eb2ca4f97909a2d2d8c91be",
          "BlockHeight": 587
        }
      }
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Stratis.FederatedPeg.Features.FederationGateway.SourceChain.RestSenderBase.SendAsync[T](T model, String route) in D:\GitHub\FederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\SourceChain\RestSenderBase.cs:line 46
```

As this is something that can happen, can we just display the error message and not the whole stack trace?

**Comment by quantumagi** [comment]
Changed the message to something useful:

![image](https://user-images.githubusercontent.com/29645989/49920214-88329f00-fefd-11e8-88d7-a9f89d858ca8.png)
