### ISSUE TITLE
Node dies while reporting its latest status

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/FederatedSidechains#288]
**Description**
The exception is thrown during normal node operation which causes the node crush.

**Logs**
[federation.zip](https://github.com/stratisproject/FederatedSidechains/files/2683078/federation.zip)

**Exception**
```
crit: Stratis.Bitcoin.FullNode[0]
      PeriodicLog threw an unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.FederatedPeg.Features.FederationGateway.FederationGatewayFeature.AddComponentStats(StringBuilder benchLog)   at Stratis.Bitcoin.Utilities.NodeStats.GetStats()
   at Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0(CancellationToken cancellation)
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext()
fail: Stratis.Bitcoin.FullNode[0]
      PeriodicLog threw an unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.FederatedPeg.Features.FederationGateway.FederationGatewayFeature.AddComponentStats(StringBuilder benchLog)
         at Stratis.Bitcoin.Utilities.NodeStats.GetStats()
         at Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0(CancellationToken cancellation)
         at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext()

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.Synchronize()
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.<>c__DisplayClass56_0.<GetTransactionsByStatusAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.SignedMultisigTransactionBroadcaster.BroadcastTransactionsAsync(ILeaderProvider leaderProvider)
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.SignedMultisigTransactionBroadcaster.<.ctor>b__6_0(ILeaderProvider m)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Code version**
```
0587481 (14 Dec @ 16:21); Patches: NugetSource,DefineFederationKeys,ChangeApiPort,AddCounterpartyHostAddress 
   
*** Build date: 15/12/2018 18:08:29.51 

*** Recent commits 
*    0587481 - (HEAD -> master, origin/master, origin/HEAD) Add agent prefix to nodes. (#282) (Fri, 14 Dec 2018 16:21:45 +0000) <Ferdeen Mughal>
*    092dbec - Model deserialization bugfix (#280) (Fri, 14 Dec 2018 17:23:19 +0300) <noescape0>
*    4142782 - RestClient for FederationGatewayController - code architecture improvements (#277) (Fri, 14 Dec 2018 17:00:39 +0300) <noescape0>
*    df3f6ab - improved the dump of NodeStore information (#275) (Fri, 14 Dec 2018 13:09:41 +0100) <MithrilMan>
*    2666e7c - Fix sidechain node in tests, differentiate between different node types, and ensure premine can be received (#274) (Fri, 14 Dec 2018 21:15:29 +1100) <Jordan Andrews>
*    3ff41a6 - Sidechain deposit + balance helper + funding main chain test (#272) (Fri, 14 Dec 2018 20:26:29 +1100) <Jordan Andrews>
*    0e5aaa4 - Add remove-transactions endpoint (#271) (Fri, 14 Dec 2018 11:20:36 +0200) <zeptin>
*    04b1ce6 - Enable fed wallets and tidy up TestBase constructor. (#265) (Fri, 14 Dec 2018 04:25:10 +0000) <Ferdeen Mughal>
*    1cc53f1 - No tracing for ConcreteConverter.ReadJson (#267) (Thu, 13 Dec 2018 18:32:14 +0000) <Jeremy Bokobza>
*    463f816 - Wallet cancellation not to throw (#262) (Thu, 13 Dec 2018 17:18:41 +0000) <Dan Gershony>  
****************** 
```

**Comment by MithrilMan** [comment]
Actually the node shouldn't explode no more because @noescape00 added a try/catch around it.
We need more informations about what was an unexpected null to see if there is a problem, but I think this issue could be closed

**Comment by bokobza** [comment]
ok, closing.
