### ISSUE TITLE
Exception during running fed gateway

### ISSUE THREAD

**Issue by noescape00** [stratisproject/FederatedSidechains#289]
Happened on 1 of the federation gateway nodes

```
      PartialTransactionRequester threw an unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.SynchronizeBatch() in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 916
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.Synchronize() in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 861
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.<>c__DisplayClass56_0.<GetTransactionsByStatusAsync>b__0() in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 1048
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.PartialTransactionRequester.<Start>b__10_0(CancellationToken token) in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\PartialTransactionRequester.cs:line 87
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 140
fail: Stratis.Bitcoin.FullNode[0]
      PartialTransactionRequester threw an unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.SynchronizeBatch() in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 916
         at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.Synchronize() in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 861
         at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.<>c__DisplayClass56_0.<GetTransactionsByStatusAsync>b__0() in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 1048
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
      --- End of stack trace from previous location where exception was thrown ---
         at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.PartialTransactionRequester.<Start>b__10_0(CancellationToken token) in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\PartialTransactionRequester.cs:line 87
         at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 140
info: Stratis.Bitcoin.Consensus.ConsensusManager[0]
      Reorg from block '2351-7519d56504144d08a329d9f2d5aff4fcbf9957e30fb29f001ff26cbba1edcdd0-FullyValidated' to '2350-93f89d3724ed09f2b06a679cab372bf480ff9e8ac6ca2a56081677632dcb6d56-FullyValidated'
info: Stratis.FederatedPeg.Features.FederationGateway.Wallet.FederationWalletSyncManager[0]
      Reorg detected, going back from '2351-7519d56504144d08a329d9f2d5aff4fcbf9957e30fb29f001ff26cbba1edcdd0-FullyValidated' to '2350-93f89d3724ed09f2b06a679cab372bf480ff9e8ac6ca2a56081677632dcb6d56-FullyValidated'.
info: Stratis.Bitcoin.FullNode[0]
      PeriodicLog stopping.
crit: Stratis.Bitcoin.FullNode[0]
      PeriodicLog threw an unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.FederatedPeg.Features.FederationGateway.FederationGatewayFeature.AddComponentStats(StringBuilder benchLog) in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\FederationGatewayFeature.cs:line 210
   at Stratis.Bitcoin.Utilities.NodeStats.GetStats() in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\NodeStats.cs:line 71
   at Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0(CancellationToken cancellation) in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\FullNode.cs:line 232
   at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 140
fail: Stratis.Bitcoin.FullNode[0]
      PeriodicLog threw an unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.FederatedPeg.Features.FederationGateway.FederationGatewayFeature.AddComponentStats(StringBuilder benchLog) in C:\Users\user\Documents\GitHub\MyForkFederatedSidechains\src\Stratis.FederatedPeg.Features.FederationGateway\FederationGatewayFeature.cs:line 210
         at Stratis.Bitcoin.Utilities.NodeStats.GetStats() in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\NodeStats.cs:line 71
         at Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0(CancellationToken cancellation) in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\FullNode.cs:line 232
         at Stratis.Bitcoin.Utilities.AsyncLoop.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in D:\GitHub\StratisBitcoinFullNode\src\Stratis.Bitcoin\Utilities\AsyncLoop.cs:line 140
```

**Comment by noescape00** [comment]
Running fed setup with full logging on. Will be able to fix it when I'll reproduce it and acquire detailed logs.

**Comment by MithrilMan** [comment]
same for #288 and #300
actually logs are generated without all the required information (NLog.config were missing some namespaces)

**Comment by noescape00** [comment]
Contacted @maciejzaleski to update logging configuration. 
Issue is postponed before new test results with full logging are there. 
Moved to retest.
