### ISSUE TITLE
Multiple nodes running in the same process will fail due to DBreezeSerializer being static.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/FederatedSidechains#297]
This means that nodes with different consensus factories can't run at the same time - the ones created later will fail when pushing to or retrieving blocks from the block store. 

This is actually more of a Full Node bug.

Offending code is here:
```
        public void Initialize(Network network)
        {
            this.Network = network;
            CustomSerializator.ByteArraySerializator = this.Serializer;
            CustomSerializator.ByteArrayDeSerializator = this.Deserializer;
        }
```

Will manifest in something like this:

```[17/12/2018 5:17:48 PM Error] The active test run was aborted. Reason: Unhandled Exception: System.IO.EndOfStreamException: No more byte to read
   at NBitcoin.BitcoinStream.ReadWriteBytes(Byte[]& data, Int32 offset, Int32 count) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\NBitcoin\BitcoinStream.cs:line 314
   at NBitcoin.BitcoinStream.ReadWrite(Byte[]& arr) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\NBitcoin\BitcoinStream.cs:line 252
   at Stratis.SmartContracts.Core.Bloom.ReadWrite(BitcoinStream stream) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.SmartContracts.Core\Bloom.cs:line 105
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\NBitcoin\BitcoinStream.cs:line 210
   at Stratis.Bitcoin.Features.SmartContracts.PoA.SmartContractPoABlockHeader.ReadWrite(BitcoinStream stream) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.Bitcoin.Features.SmartContracts\PoA\SmartContractPoABlockHeader.cs:line 39
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\NBitcoin\BitcoinStream.cs:line 210
   at NBitcoin.Block.ReadWrite(BitcoinStream stream) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\NBitcoin\Block.cs:line 56
   at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Stream stream, Boolean serializing, ConsensusFactory consensusFactory, ProtocolVersion protocolVersion) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\NBitcoin\IBitcoinSerializable.cs:line 27
   at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Byte[] bytes, ConsensusFactory consensusFactory, ProtocolVersion version) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\NBitcoin\IBitcoinSerializable.cs:line 41
   at NBitcoin.Block.Load(Byte[] bytes, Network network) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\NBitcoin\Block.cs:line 183
   at Stratis.Bitcoin.Utilities.DBreezeSerializer.Deserializer(Byte[] bytes, Type type) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.Bitcoin\Utilities\DBreezeSerializer.cs:line 119
   at DBreeze.DataTypes.DataTypesConvertor.ConvertBack[TData](Byte[] dt)
   at DBreeze.DataTypes.Row`2.get_Value()
   at Stratis.Bitcoin.Features.BlockStore.BlockRepository.GetBlocksFromHashes(Transaction dbreezeTransaction, List`1 hashes) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.Bitcoin.Features.BlockStore\BlockRepository.cs:line 484
   at Stratis.Bitcoin.Features.BlockStore.BlockRepository.<>c__DisplayClass32_0.<GetBlocksAsync>b__0() in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.Bitcoin.Features.BlockStore\BlockRepository.cs:line 414
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.SynchronizeBatch() in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 936
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.Synchronize() in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 890
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.<>c__DisplayClass56_0.<GetTransactionsByStatusAsync>b__0() in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\CrossChainTransferStore.cs:line 1077
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.SignedMultisigTransactionBroadcaster.BroadcastTransactionsAsync(ILeaderProvider leaderProvider) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\SignedMultisigTransactionBroadcaster.cs:line 52
   at Stratis.FederatedPeg.Features.FederationGateway.TargetChain.SignedMultisigTransactionBroadcaster.<.ctor>b__6_0(ILeaderProvider m) in C:\Users\jorda\source\repos\StratisBitcoinFullNode3\src\Stratis.FederatedPeg.Features.FederationGateway\TargetChain\SignedMultisigTransactionBroadcaster.cs:line 43
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()```

**Comment by quantumagi** [comment]
This is the gist of the problem:

`Row<byte[], Block> blockRow = dbreezeTransaction.Select<byte[], Block>(BlockTableName, key.Item2);`

Thinking purely theoretically, notice that the only information available to the serializer would be the object type: `Block`. Re-usability of code like this is impaired if other networks (running simultaneously) want to store the block differently - no additional instructions can be sent via the above call. Also, any static information that we try to provide may be overwritten. (edited)

This suggest that the only answer is a *custom dbreeze transaction class* that delegates to the dbreeze transaction. Such a class could for instance read a block as a byte array and then use a method on the consensus factory to turn that into a network-specific block type.

**Comment by rowandh** [comment]
There's no nice and easy solution to this. Rather than hack something together with statics, I think the right course of action is to remove the byte array serializers from DBreeze. We can do that a couple of ways:
1. Serialize/deserialize to byte[] as required when creating the transaction. Not too hard, it's not used in *that* many places.
2. Create our own DBreezeEngine adapter, which wraps `GetTransaction()` and returns a custom transaction object that knows how to serialize/deserialize different object types.

Of these, I prefer option 1 because I don't think serialization should be the responsibility of the database engine.
